Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
